export default function badWordsFilter(texto) {
  
  var badWords = new Array(
                    "anal",
                    "argentuzo",
                    "argentuso",
                    "argentuchoadefesio",
                    "asco",
                    "asqueroso",
                    "asquerosa",
                    "balurde ",
                    "boludo",
                    "bolú",
                    "bolu",
                    "boludo",
                    "b0ludo",
                    "bolud0",
                    "b0lud0",
                    "boluda",
                    "b0luda",
                    "caka",
                    "Cabrón",
                    "cabrónes",
                    "cabrona",
                    "cachimba ",
                    "cagar",
                    "cagalera",
                    "caga",
                    "cagarla",
                    "cagaste",
                    "cagaste",
                    "cagón",
                    "cagon",
                    "cagona",
                    "coñaso",
                    "Cornudo ",
                    "Culeado ",
                    "culero",
                    "carajo ",
                    "concha",
                    "Conchudo ",
                    "coño",
                    "coñazo",
                    "culea",
                    "culear",
                    "culiado",
                    "culiada",
                    "culiao",
                    "culia",
                    "culiad@",
                    "culo",
                    "cerote",
                    "cojón",
                    "cojido",
                    "cojones",
                    "Comemierda",
                    "gilipoya",
                    "gonorrea",
                    "guevon",
                    "guevón",
                    "guevona",
                    "garcha",
                    "gilipolla",
                    "guatepeor",
                    "heil",
                    "hideputa",
                    "hijodeputa",
                    "hijoputa",
                    "hdp",
                    "huevon",
                    "huevón",
                    "huevona",
                    "HWDP",
                    "jodan",
                    "jodas",
                    "jodaz",
                    "joder",
                    "jodido",
                    "jilipoya",
                    "jilipolla",
                    "estupido",
                    "estúpido",
                    "estupida",
                    "estúpida",
                    "emputar",
                    "enputar",
                    "emputo",
                    "enputo",
                    "empute",
                    "emputado",
                    "enputado",
                    "encular",
                    "follada",
                    "follar",
                    "follo",
                    "follón",
                    "follon",
                    "chinga",
                    "chingar",
                    "chucha",
                    "chingada",
                    "chingado",
                    "chíngate",
                    "chingas",
                    "chingaste",
                    "chingo",
                    "chingon",
                    "chingón",
                    "chingona",
                    "chingues",
                    "chupa",
                    "chupalo",
                    "chúpalo",
                    "chúpala",
                    "chupala",
                    "mierda",
                    "gilipollas",
                    "Jilipollas",
                    "joder",
                    "Mula",
                    "malnacida",
                    "Malnacido",
                    "malparida",
                    "malparido",
                    "perra",
                    "mamaguevo",
                    "mamon",
                    "maricon",
                    "mamada",
                    "mamado",
                    "mamalo",
                    "mámalo",
                    "mamarla",
                    "mamón",
                    "mamon",
                    "mamona",
                    "manco",
                    "manko",
                    "manca",
                    "maraca",
                    "Marica",
                    "marico",
                    "Maricon",
                    "Maricón",
                    "maricones",
                    "maricona",
                    "mariconas",
                    "mariconson",
                    "mariconsón",
                    "mariconzón",
                    "mariconzon",
                    "mariqueta",
                    "mariquis",
                    "mierda",
                    "m1erda",
                    "mierdas",
                    "m1erdas",
                    "mierdero",
                    "orto",
                    "ojete",
                    "ogete",
                    "pajear",
                    "pajote",
                    "puta",
                    "pollas",
                    "polla",
                    "perras",
                    "Pajero ",
                    "Panocha ",
                    "papallona",
                    "Papayona ",
                    "Pelotudo ",
                    "pendejo",
                    "pinche",
                    "pinga",
                    "pedo",
                    "pedofila",
                    "pedófila",
                    "pedofilo",
                    "pedófilo",
                    "pedón",
                    "pendeja",
                    "pendejo",
                    "pendejos",
                    "pelotudo",
                    "pel0tud0",
                    "pelotuda",
                    "pel0tuda",
                    "pene",
                    "percanta",
                    "perra",
                    "pinche",
                    "pinga",
                    "pirobo",
                    "pito",
                    "pitudo",
                    "pizda",
                    "polla",
                    "porno",
                    "poronga",
                    "poya",
                    "prostiputo",
                    "prostiputa",
                    "prostituir",
                    "prostituta",
                    "prostituto",
                    "proxeneta",
                    "putas",
                    "Puñeta",
                    "Pussy",
                    "puta",
                    "Putain",
                    "Putaso",
                    "Putazo",
                    "pute",
                    "Pute",
                    "Putete",
                    "putillo",
                    "putiyo",
                    "putito",
                    "putita",
                    "putitos",
                    "putitas",
                    "Putiza",
                    "puto",
                    "putos",
                    "putón",
                    "Perucho",
                    "Lolas",
                    "kaka",
                    "kaca ",
                    "ramera",
                    "rape",
                    "Soplanucas ",
                    "Tarado ",
                    "Vejiga ",
                    "verga",
                    "verga",
                    "vergasen",
                    "vergón",
                    "vergon",
                    "violar",
                    "Violer",
                    "zemen",
                    "zooplapollas",
                    "zoplapollas",
                    "zorra",
                    "zorriputa",
                    "zorriput@",
                    "zudaca",
                    "zudaka",
                    "zorra"
                  );
  
  var txtArray = texto.trim().split(" ");
  
  var txtCleanArray = [];

  for(index of txtArray){
    if (index == "") {
      //console.log("String vacio encontrado..!");
    }else{
      txtCleanArray.push(index);
    }
  }

  //console.log(txtCleanArray);

  var badWordsFound = [];

  var regExp = new RegExp("^"+badWords.join("$|^")+"$","gi");

  for (index of txtCleanArray) {
    var match = index.match(regExp)
    if (match != null) {
      badWordsFound.push(match[0]);
    }
    
  }
  var msj = "";
  for (index of badWordsFound) {
    msj+="' " + index + " '\n";
  }
  //console.log(badWordsFound);
  if (badWordsFound.length > 0 ) {
    return {msj:'Se encontraron palabras ofensivas en su comentario :\n' + msj, result:false };
    
  }
  return {result : true};
}

